/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToldosRouteImport } from './routes/toldos'
import { Route as TelaMosquiteiraRouteImport } from './routes/tela-mosquiteira'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoloBlackoutTexturizadoRouteImport } from './routes/rolo-blackout-texturizado'
import { Route as RoloBlackoutPinpointRouteImport } from './routes/rolo-blackout-pinpoint'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PersianaVerticalRouteImport } from './routes/persiana-vertical'
import { Route as PersianaSolarScreenRouteImport } from './routes/persiana-solar-screen'
import { Route as PersianaRoloBlackoutRouteImport } from './routes/persiana-rolo-blackout'
import { Route as PersianaRioDeJaneiroRouteImport } from './routes/persiana-rio-de-janeiro'
import { Route as PersianaPainelRouteImport } from './routes/persiana-painel'
import { Route as PersianaJuizDeForaRouteImport } from './routes/persiana-juiz-de-fora'
import { Route as PersianaHorizontalRouteImport } from './routes/persiana-horizontal'
import { Route as PersianaDoubleVisionRouteImport } from './routes/persiana-double-vision'
import { Route as PersianaBeloHorizonteRouteImport } from './routes/persiana-belo-horizonte'
import { Route as CortinaRomanaRouteImport } from './routes/cortina-romana'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as PedidoNumeroRouteImport } from './routes/pedido.$numero'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminSiteRouteImport } from './routes/admin.site'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminProducaoRouteImport } from './routes/admin.producao'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminOrcamentosRouteImport } from './routes/admin.orcamentos'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminLumiConfigRouteImport } from './routes/admin.lumi-config'
import { Route as AdminLumiRouteImport } from './routes/admin.lumi'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminIntegracoesRouteImport } from './routes/admin.integracoes'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminCatalogoRouteImport } from './routes/admin.catalogo'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api.public.asaas-webhook'

const ToldosRoute = ToldosRouteImport.update({
  id: '/toldos',
  path: '/toldos',
  getParentRoute: () => rootRouteImport,
} as any)
const TelaMosquiteiraRoute = TelaMosquiteiraRouteImport.update({
  id: '/tela-mosquiteira',
  path: '/tela-mosquiteira',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoloBlackoutTexturizadoRoute = RoloBlackoutTexturizadoRouteImport.update({
  id: '/rolo-blackout-texturizado',
  path: '/rolo-blackout-texturizado',
  getParentRoute: () => rootRouteImport,
} as any)
const RoloBlackoutPinpointRoute = RoloBlackoutPinpointRouteImport.update({
  id: '/rolo-blackout-pinpoint',
  path: '/rolo-blackout-pinpoint',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PersianaVerticalRoute = PersianaVerticalRouteImport.update({
  id: '/persiana-vertical',
  path: '/persiana-vertical',
  getParentRoute: () => rootRouteImport,
} as any)
const PersianaSolarScreenRoute = PersianaSolarScreenRouteImport.update({
  id: '/persiana-solar-screen',
  path: '/persiana-solar-screen',
  getParentRoute: () => rootRouteImport,
} as any)
const PersianaRoloBlackoutRoute = PersianaRoloBlackoutRouteImport.update({
  id: '/persiana-rolo-blackout',
  path: '/persiana-rolo-blackout',
  getParentRoute: () => rootRouteImport,
} as any)
const PersianaRioDeJaneiroRoute = PersianaRioDeJaneiroRouteImport.update({
  id: '/persiana-rio-de-janeiro',
  path: '/persiana-rio-de-janeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const PersianaPainelRoute = PersianaPainelRouteImport.update({
  id: '/persiana-painel',
  path: '/persiana-painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PersianaJuizDeForaRoute = PersianaJuizDeForaRouteImport.update({
  id: '/persiana-juiz-de-fora',
  path: '/persiana-juiz-de-fora',
  getParentRoute: () => rootRouteImport,
} as any)
const PersianaHorizontalRoute = PersianaHorizontalRouteImport.update({
  id: '/persiana-horizontal',
  path: '/persiana-horizontal',
  getParentRoute: () => rootRouteImport,
} as any)
const PersianaDoubleVisionRoute = PersianaDoubleVisionRouteImport.update({
  id: '/persiana-double-vision',
  path: '/persiana-double-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const PersianaBeloHorizonteRoute = PersianaBeloHorizonteRouteImport.update({
  id: '/persiana-belo-horizonte',
  path: '/persiana-belo-horizonte',
  getParentRoute: () => rootRouteImport,
} as any)
const CortinaRomanaRoute = CortinaRomanaRouteImport.update({
  id: '/cortina-romana',
  path: '/cortina-romana',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoNumeroRoute = PedidoNumeroRouteImport.update({
  id: '/pedido/$numero',
  path: '/pedido/$numero',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteRoute = AdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProducaoRoute = AdminProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrcamentosRoute = AdminOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLumiConfigRoute = AdminLumiConfigRouteImport.update({
  id: '/lumi-config',
  path: '/lumi-config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLumiRoute = AdminLumiRouteImport.update({
  id: '/lumi',
  path: '/lumi',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegracoesRoute = AdminIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogoRoute = AdminCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRoute
  '/cortina-romana': typeof CortinaRomanaRoute
  '/persiana-belo-horizonte': typeof PersianaBeloHorizonteRoute
  '/persiana-double-vision': typeof PersianaDoubleVisionRoute
  '/persiana-horizontal': typeof PersianaHorizontalRoute
  '/persiana-juiz-de-fora': typeof PersianaJuizDeForaRoute
  '/persiana-painel': typeof PersianaPainelRoute
  '/persiana-rio-de-janeiro': typeof PersianaRioDeJaneiroRoute
  '/persiana-rolo-blackout': typeof PersianaRoloBlackoutRoute
  '/persiana-solar-screen': typeof PersianaSolarScreenRoute
  '/persiana-vertical': typeof PersianaVerticalRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rolo-blackout-pinpoint': typeof RoloBlackoutPinpointRoute
  '/rolo-blackout-texturizado': typeof RoloBlackoutTexturizadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tela-mosquiteira': typeof TelaMosquiteiraRoute
  '/toldos': typeof ToldosRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/lumi': typeof AdminLumiRoute
  '/admin/lumi-config': typeof AdminLumiConfigRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/producao': typeof AdminProducaoRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/pedido/$numero': typeof PedidoNumeroRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRoute
  '/cortina-romana': typeof CortinaRomanaRoute
  '/persiana-belo-horizonte': typeof PersianaBeloHorizonteRoute
  '/persiana-double-vision': typeof PersianaDoubleVisionRoute
  '/persiana-horizontal': typeof PersianaHorizontalRoute
  '/persiana-juiz-de-fora': typeof PersianaJuizDeForaRoute
  '/persiana-painel': typeof PersianaPainelRoute
  '/persiana-rio-de-janeiro': typeof PersianaRioDeJaneiroRoute
  '/persiana-rolo-blackout': typeof PersianaRoloBlackoutRoute
  '/persiana-solar-screen': typeof PersianaSolarScreenRoute
  '/persiana-vertical': typeof PersianaVerticalRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rolo-blackout-pinpoint': typeof RoloBlackoutPinpointRoute
  '/rolo-blackout-texturizado': typeof RoloBlackoutTexturizadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tela-mosquiteira': typeof TelaMosquiteiraRoute
  '/toldos': typeof ToldosRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/lumi': typeof AdminLumiRoute
  '/admin/lumi-config': typeof AdminLumiConfigRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/producao': typeof AdminProducaoRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/pedido/$numero': typeof PedidoNumeroRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/catalogo': typeof CatalogoRoute
  '/cortina-romana': typeof CortinaRomanaRoute
  '/persiana-belo-horizonte': typeof PersianaBeloHorizonteRoute
  '/persiana-double-vision': typeof PersianaDoubleVisionRoute
  '/persiana-horizontal': typeof PersianaHorizontalRoute
  '/persiana-juiz-de-fora': typeof PersianaJuizDeForaRoute
  '/persiana-painel': typeof PersianaPainelRoute
  '/persiana-rio-de-janeiro': typeof PersianaRioDeJaneiroRoute
  '/persiana-rolo-blackout': typeof PersianaRoloBlackoutRoute
  '/persiana-solar-screen': typeof PersianaSolarScreenRoute
  '/persiana-vertical': typeof PersianaVerticalRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/rolo-blackout-pinpoint': typeof RoloBlackoutPinpointRoute
  '/rolo-blackout-texturizado': typeof RoloBlackoutTexturizadoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tela-mosquiteira': typeof TelaMosquiteiraRoute
  '/toldos': typeof ToldosRoute
  '/admin/catalogo': typeof AdminCatalogoRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/lumi': typeof AdminLumiRoute
  '/admin/lumi-config': typeof AdminLumiConfigRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/producao': typeof AdminProducaoRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/pedido/$numero': typeof PedidoNumeroRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/catalogo'
    | '/cortina-romana'
    | '/persiana-belo-horizonte'
    | '/persiana-double-vision'
    | '/persiana-horizontal'
    | '/persiana-juiz-de-fora'
    | '/persiana-painel'
    | '/persiana-rio-de-janeiro'
    | '/persiana-rolo-blackout'
    | '/persiana-solar-screen'
    | '/persiana-vertical'
    | '/robots.txt'
    | '/rolo-blackout-pinpoint'
    | '/rolo-blackout-texturizado'
    | '/sitemap.xml'
    | '/tela-mosquiteira'
    | '/toldos'
    | '/admin/catalogo'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/integracoes'
    | '/admin/leads'
    | '/admin/lumi'
    | '/admin/lumi-config'
    | '/admin/marketing'
    | '/admin/orcamentos'
    | '/admin/pedidos'
    | '/admin/producao'
    | '/admin/relatorios'
    | '/admin/site'
    | '/admin/usuarios'
    | '/blog/$slug'
    | '/pedido/$numero'
    | '/produto/$slug'
    | '/admin/'
    | '/blog/'
    | '/api/public/asaas-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/catalogo'
    | '/cortina-romana'
    | '/persiana-belo-horizonte'
    | '/persiana-double-vision'
    | '/persiana-horizontal'
    | '/persiana-juiz-de-fora'
    | '/persiana-painel'
    | '/persiana-rio-de-janeiro'
    | '/persiana-rolo-blackout'
    | '/persiana-solar-screen'
    | '/persiana-vertical'
    | '/robots.txt'
    | '/rolo-blackout-pinpoint'
    | '/rolo-blackout-texturizado'
    | '/sitemap.xml'
    | '/tela-mosquiteira'
    | '/toldos'
    | '/admin/catalogo'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/integracoes'
    | '/admin/leads'
    | '/admin/lumi'
    | '/admin/lumi-config'
    | '/admin/marketing'
    | '/admin/orcamentos'
    | '/admin/pedidos'
    | '/admin/producao'
    | '/admin/relatorios'
    | '/admin/site'
    | '/admin/usuarios'
    | '/blog/$slug'
    | '/pedido/$numero'
    | '/produto/$slug'
    | '/admin'
    | '/blog'
    | '/api/public/asaas-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/catalogo'
    | '/cortina-romana'
    | '/persiana-belo-horizonte'
    | '/persiana-double-vision'
    | '/persiana-horizontal'
    | '/persiana-juiz-de-fora'
    | '/persiana-painel'
    | '/persiana-rio-de-janeiro'
    | '/persiana-rolo-blackout'
    | '/persiana-solar-screen'
    | '/persiana-vertical'
    | '/robots.txt'
    | '/rolo-blackout-pinpoint'
    | '/rolo-blackout-texturizado'
    | '/sitemap.xml'
    | '/tela-mosquiteira'
    | '/toldos'
    | '/admin/catalogo'
    | '/admin/categorias'
    | '/admin/configuracoes'
    | '/admin/financeiro'
    | '/admin/integracoes'
    | '/admin/leads'
    | '/admin/lumi'
    | '/admin/lumi-config'
    | '/admin/marketing'
    | '/admin/orcamentos'
    | '/admin/pedidos'
    | '/admin/producao'
    | '/admin/relatorios'
    | '/admin/site'
    | '/admin/usuarios'
    | '/blog/$slug'
    | '/pedido/$numero'
    | '/produto/$slug'
    | '/admin/'
    | '/blog/'
    | '/api/public/asaas-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CatalogoRoute: typeof CatalogoRoute
  CortinaRomanaRoute: typeof CortinaRomanaRoute
  PersianaBeloHorizonteRoute: typeof PersianaBeloHorizonteRoute
  PersianaDoubleVisionRoute: typeof PersianaDoubleVisionRoute
  PersianaHorizontalRoute: typeof PersianaHorizontalRoute
  PersianaJuizDeForaRoute: typeof PersianaJuizDeForaRoute
  PersianaPainelRoute: typeof PersianaPainelRoute
  PersianaRioDeJaneiroRoute: typeof PersianaRioDeJaneiroRoute
  PersianaRoloBlackoutRoute: typeof PersianaRoloBlackoutRoute
  PersianaSolarScreenRoute: typeof PersianaSolarScreenRoute
  PersianaVerticalRoute: typeof PersianaVerticalRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RoloBlackoutPinpointRoute: typeof RoloBlackoutPinpointRoute
  RoloBlackoutTexturizadoRoute: typeof RoloBlackoutTexturizadoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TelaMosquiteiraRoute: typeof TelaMosquiteiraRoute
  ToldosRoute: typeof ToldosRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PedidoNumeroRoute: typeof PedidoNumeroRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/toldos': {
      id: '/toldos'
      path: '/toldos'
      fullPath: '/toldos'
      preLoaderRoute: typeof ToldosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tela-mosquiteira': {
      id: '/tela-mosquiteira'
      path: '/tela-mosquiteira'
      fullPath: '/tela-mosquiteira'
      preLoaderRoute: typeof TelaMosquiteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rolo-blackout-texturizado': {
      id: '/rolo-blackout-texturizado'
      path: '/rolo-blackout-texturizado'
      fullPath: '/rolo-blackout-texturizado'
      preLoaderRoute: typeof RoloBlackoutTexturizadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rolo-blackout-pinpoint': {
      id: '/rolo-blackout-pinpoint'
      path: '/rolo-blackout-pinpoint'
      fullPath: '/rolo-blackout-pinpoint'
      preLoaderRoute: typeof RoloBlackoutPinpointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persiana-vertical': {
      id: '/persiana-vertical'
      path: '/persiana-vertical'
      fullPath: '/persiana-vertical'
      preLoaderRoute: typeof PersianaVerticalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persiana-solar-screen': {
      id: '/persiana-solar-screen'
      path: '/persiana-solar-screen'
      fullPath: '/persiana-solar-screen'
      preLoaderRoute: typeof PersianaSolarScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persiana-rolo-blackout': {
      id: '/persiana-rolo-blackout'
      path: '/persiana-rolo-blackout'
      fullPath: '/persiana-rolo-blackout'
      preLoaderRoute: typeof PersianaRoloBlackoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persiana-rio-de-janeiro': {
      id: '/persiana-rio-de-janeiro'
      path: '/persiana-rio-de-janeiro'
      fullPath: '/persiana-rio-de-janeiro'
      preLoaderRoute: typeof PersianaRioDeJaneiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persiana-painel': {
      id: '/persiana-painel'
      path: '/persiana-painel'
      fullPath: '/persiana-painel'
      preLoaderRoute: typeof PersianaPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persiana-juiz-de-fora': {
      id: '/persiana-juiz-de-fora'
      path: '/persiana-juiz-de-fora'
      fullPath: '/persiana-juiz-de-fora'
      preLoaderRoute: typeof PersianaJuizDeForaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persiana-horizontal': {
      id: '/persiana-horizontal'
      path: '/persiana-horizontal'
      fullPath: '/persiana-horizontal'
      preLoaderRoute: typeof PersianaHorizontalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persiana-double-vision': {
      id: '/persiana-double-vision'
      path: '/persiana-double-vision'
      fullPath: '/persiana-double-vision'
      preLoaderRoute: typeof PersianaDoubleVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persiana-belo-horizonte': {
      id: '/persiana-belo-horizonte'
      path: '/persiana-belo-horizonte'
      fullPath: '/persiana-belo-horizonte'
      preLoaderRoute: typeof PersianaBeloHorizonteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cortina-romana': {
      id: '/cortina-romana'
      path: '/cortina-romana'
      fullPath: '/cortina-romana'
      preLoaderRoute: typeof CortinaRomanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$numero': {
      id: '/pedido/$numero'
      path: '/pedido/$numero'
      fullPath: '/pedido/$numero'
      preLoaderRoute: typeof PedidoNumeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site': {
      id: '/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AdminSiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/producao': {
      id: '/admin/producao'
      path: '/producao'
      fullPath: '/admin/producao'
      preLoaderRoute: typeof AdminProducaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orcamentos': {
      id: '/admin/orcamentos'
      path: '/orcamentos'
      fullPath: '/admin/orcamentos'
      preLoaderRoute: typeof AdminOrcamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lumi-config': {
      id: '/admin/lumi-config'
      path: '/lumi-config'
      fullPath: '/admin/lumi-config'
      preLoaderRoute: typeof AdminLumiConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lumi': {
      id: '/admin/lumi'
      path: '/lumi'
      fullPath: '/admin/lumi'
      preLoaderRoute: typeof AdminLumiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integracoes': {
      id: '/admin/integracoes'
      path: '/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AdminIntegracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogo': {
      id: '/admin/catalogo'
      path: '/catalogo'
      fullPath: '/admin/catalogo'
      preLoaderRoute: typeof AdminCatalogoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCatalogoRoute: typeof AdminCatalogoRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminIntegracoesRoute: typeof AdminIntegracoesRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLumiRoute: typeof AdminLumiRoute
  AdminLumiConfigRoute: typeof AdminLumiConfigRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminOrcamentosRoute: typeof AdminOrcamentosRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProducaoRoute: typeof AdminProducaoRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminSiteRoute: typeof AdminSiteRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogoRoute: AdminCatalogoRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminIntegracoesRoute: AdminIntegracoesRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLumiRoute: AdminLumiRoute,
  AdminLumiConfigRoute: AdminLumiConfigRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminOrcamentosRoute: AdminOrcamentosRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProducaoRoute: AdminProducaoRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminSiteRoute: AdminSiteRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CatalogoRoute: CatalogoRoute,
  CortinaRomanaRoute: CortinaRomanaRoute,
  PersianaBeloHorizonteRoute: PersianaBeloHorizonteRoute,
  PersianaDoubleVisionRoute: PersianaDoubleVisionRoute,
  PersianaHorizontalRoute: PersianaHorizontalRoute,
  PersianaJuizDeForaRoute: PersianaJuizDeForaRoute,
  PersianaPainelRoute: PersianaPainelRoute,
  PersianaRioDeJaneiroRoute: PersianaRioDeJaneiroRoute,
  PersianaRoloBlackoutRoute: PersianaRoloBlackoutRoute,
  PersianaSolarScreenRoute: PersianaSolarScreenRoute,
  PersianaVerticalRoute: PersianaVerticalRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RoloBlackoutPinpointRoute: RoloBlackoutPinpointRoute,
  RoloBlackoutTexturizadoRoute: RoloBlackoutTexturizadoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TelaMosquiteiraRoute: TelaMosquiteiraRoute,
  ToldosRoute: ToldosRoute,
  BlogSlugRoute: BlogSlugRoute,
  PedidoNumeroRoute: PedidoNumeroRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
